---
title: "growth_2"
author: "Kane Russell"
date: "12/9/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#install.packages("ggpubr")
library(ggpubr)
```

## Data

```{r}
treatments <- data.frame(TRT = c("M", "MH", "MBB", "BB"), 
                         Treatment = c("Mastication Only", "Mastication + Herbicide", "Mastication + Burn", "Burn Only" ))
treatments

RBAI_gap <- 
  read.csv("grow_RBA_ac.csv") %>% 
  mutate(COMPGAP = paste0(COMP, GAP)) %>% 
  mutate(RBAI = (BA_18_AC - BA_13_AC)/(BA_13_AC*5)) %>% 
  arrange(factor(TRT, levels = c("M", "MH", "MBB", "BB"))) %>% 
  left_join(treatments) %>% 
  select(TRT, Treatment, COMPGAP, RBAI)
RBAI_gap
```

## ANOVA

```{r}
RBAI_aov <- aov(RBAI ~ TRT, data = RBAI_gap)
sum_RBAI_aov <- summary(RBA_aov)
sum_RBAI_aov
```


## Tukey's HSD

```{r}
Tuk_RBAI <- TukeyHSD(RBAI_aov)
Tuk_RBAI
plot(Tuk_RBAI)
```



## Plotting

```{r}
 ggplot() + 
  geom_boxplot(data = RBAI_gap, 
               aes(x = factor(Treatment, c("Mastication + Herbicide", "Mastication Only",  "Mastication + Burn", "Burn Only")), 
                   y = RBAI)) + 
  #geom_bracket(xmin = "Mastication + Herbicide", xmax = "Mastication + Burn", 
  #             y.position = 0.26, label = "") +
  #geom_bracket(x = "Mastication + Herbicide", xmax = "Mastication Only", 
  #             y.position =  0.26, label = "") +
  #geom_bracket(x = "Mastication Only", xmax = "Burn Only", 
  #             y.position = 0.25, label = "") +
  #geom_bracket(x = "Mastication Only", xmax = "Mastication + Burn", 
  #             y.position = 0.25, label = "") +
  #geom_bracket(x = "Mastication + Burn", xmax = "Burn Only", 
  #             y.position = 0.25, label = "") +
  geom_segment(aes(x = "Mastication + Herbicide", xend = "Mastication + Burn", 
                   y = 0.48, yend = 0.48)) + 
  geom_segment(aes(x = "Mastication Only", xend = "Burn Only", 
                   y = 0.465, yend = 0.465)) + 
  labs(x = "Treatment", 
       y = "Relative basal area increment (%/year)", 
       caption = "Note: Horizontal lines indicate treatments that are not significantly different using Tukey's HSD", 
       title = "Growth response by treatment") #+ 
  #geom_text(aes(x = c("Mastication + Herbicide", "Mastication Only",  "Mastication + Burn", "Burn Only"), 
  #              y = c(0.47, 0.335, 0.26, 0.195), 
  #              label = c("a", "a  b", "a  b", "b")))
```

```{r}
tky <- as.data.frame(Tuk_RBA$TRT)
tky$pair <- rownames(tky)
  ggplot(tky, aes(colour=cut(`p adj`, c(0, 0.01, 0.05, 1), 
                           label=c("p<0.01","p<0.05","Non-Sig")))) +
  geom_hline(yintercept=0, lty="11", colour="grey30") +
  geom_errorbar(aes(pair, ymin=lwr, ymax=upr), width=0.2) +
  geom_point(aes(pair, diff)) +
  labs(colour="")
  
```


Chi-Squares Analysis

```{r}
growth <- 
  read.csv("TAYSR_CompiledGrowthData_2013_2018.csv")
colnames(growth)[colnames(growth)=="TREATMENT"] <- "TRT"
colnames(growth)[colnames(growth)=="SPECIES"] <- "SPP"
growth_out <- growth[-c(153),]
fgrow <- 
  growth_out %>% 
  filter(SPP %in% c("DF", "IC", "PP", "SP", "WF"))

spp_comp <-
  table(growth_out$COMPGAP, growth_out$SPP)
spp_comp
```


```{r}
#install.packages("corrplot")
library(corrplot)
chisq <- chisq.test(spp_comp)
chisq
```

```{r}
contrib <- 100*chisq$residuals^2/chisq$statistic
corrplot(contrib, is.cor = FALSE)
```


```{r}
GS_comp <- 
  as.data.frame(spp_comp[, 3]) %>% 
  rename('GS' = 'spp_comp[, 3]') %>% 
  mutate(COMPGAP = rownames(spp_comp), 
         PRESENCE = GS>0) %>% 
  left_join(RBAI_gap) %>% 
  select(TRT, COMPGAP, PRESENCE, RBAI)
GS_comp
```

```{r}
AOV2_fit <- aov(RBAI ~ PRESENCE*TRT, data = GS_comp)
summary(AOV2_fit)
```


```{r}
pd <- position_dodge(0.4)
GS_comp %>% 
  group_by(TRT, PRESENCE) %>% 
  summarise(mean = mean(RBAI)) %>% 
  ggplot() + 
  geom_point(aes(x = factor(TRT, levels = c("MH", "M", "MBB", "BB")), 
                 y = mean, 
                 color = PRESENCE), 
             position = pd, 
             shape = 15, 
             size = 3)
```

