---
title: "thesis_growth"
author: "Kane Russell"
date: "9/9/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(nlme)
library(dplyr)
library(car)
library(plotly)
```

```{r}
growth <- 
  read.csv("TAYSR_CompiledGrowthData_2013_2018.csv")
growth <- 
  growth %>% 
  mutate(RGR_BA = BAI/BA_2013)
growth$COMP <- factor(growth$COMP)
colnames(growth)[colnames(growth)=="TREATMENT"] <- "TRT"
colnames(growth)[colnames(growth)=="SPECIES"] <- "SPP"
head(growth)
```

```{r}
growth_out <- growth[-c(153),] 
growth_out
```


### Initial Data Visualization

```{r}
ANNINC_boxplot <- 
  ggplot(growth) + 
  geom_boxplot(aes(x = TRT, y = ANN_INC), varwidth = TRUE)
ANNINC_boxplot
```

```{r}
RGR_boxplot <- 
  ggplot(growth_out) + 
  geom_boxplot(aes(x = TRT, y = RGR), varwidth = TRUE)
RGR_boxplot
```

```{r}
BAI_boxplot <- 
  ggplot(growth) + 
  geom_boxplot(aes(x = TRT, y = BAI), varwidth = TRUE)
BAI_boxplot
```









```{r}
mean_ANN_INC <- summarize(group_by(growth, TRT), mean_ANN_INC = mean(ANN_INC))
mean_ANN_INC
```


```{r}
ANN_INC_by_trt <- 
  ggplot() + 
  geom_boxplot(data = growth, aes(x = TRT, y = ANN_INC, group = COMPGAP, color = COMP)) + 
  geom_point(data = mean_ANN_INC, aes(x = TRT, y = mean_ANN_INC), color = "red", shape = 4, size = 4)
ANN_INC_by_trt
```
```{r}
mean_RGR <- summarize(group_by(growth_out, TRT), mean_RGR = mean(RGR))
mean_RGR
```


```{r}
RGR_by_trt <- 
  ggplot() + 
  geom_boxplot(data = growth_out, aes(x = TRT, y = RGR, group = COMPGAP, color = factor(COMP))) + 
  geom_point(data = mean_RGR, aes(x = TRT, y = mean_RGR), color = "red", shape = 4, size = 4)
RGR_by_trt
```


```{r}
mean_BAI <- summarize(group_by(growth, TRT), mean_BAI = mean(BAI))
mean_BAI
BAI_by_trt <- 
  ggplot() + 
  geom_boxplot(data = growth, aes(x = TRT, y = BAI, group = COMPGAP, color = COMP)) + 
  geom_point(data = mean_BAI, aes(x = TRT, y = mean_BAI), color = "red", shape = 4, size = 4)
BAI_by_trt
```

```{r}
mean_RGR_BA <- summarize(group_by(growth_out, TRT), mean_RGR_BA = mean(RGR_BA))
mean_RGR_BA
RGR_BA_by_trt <- 
  ggplot() + 
  geom_boxplot(data = growth_out, aes(x = TRT, y = RGR_BA, group = COMPGAP, color = factor(COMP))) + 
  geom_point(data = mean_RGR_BA, aes(x = TRT, y = mean_RGR_BA), color = "red", shape = 4, size = 4)
RGR_BA_by_trt
```


```{r}
ANN_INC_spp <- 
  ggplot(growth) + 
  geom_boxplot(aes(x = SPP, y = ANN_INC))
ANN_INC_spp

RGR_spp <- 
  ggplot(growth) + 
  geom_boxplot(aes(x = SPP, y = RGR))
RGR_spp

BAI_spp <- 
  ggplot(growth) + 
  geom_boxplot(aes(x = SPP, y = BAI))
BAI_spp

RGR_BA_spp <-
  ggplot(growth_out) + 
  geom_boxplot(aes(x = SPP, y = RGR_BA))
RGR_BA_spp
```




### Modeling

```{r}
M.lm <- gls(ANN_INC ~ TRT + SPP, data = growth)
plot(resid(M.lm) ~ growth$TRT)
plot(resid(M.lm) ~ growth$SPP)
summary(M.lm)
```

```{r}
vf2 <- varIdent(form= ~ 1 | TRT * SPP)
M.identvar <- gls(ANN_INC ~ TRT + SPP, data = growth, weights = vf2)
summary(M.identvar)
```

```{r}
E2 <- resid(M.identvar, type = "normalized")
coplot(E2 ~ TRT | SPP, data = growth,
ylab = "Normalised residuals")
```

```{r}
anova(M.lm, M.identvar)
```

```{r}
M.lm2 <- lm(data = growth, RGR ~ TRT + SPP + COMP + TRT:SPP)
summary(M.lm2)
```


```{r}
Z <- cbind(growth$TRT, growth$SPP, growth$COMP,
growth$P_NP, growth$HTCB_2013)
colnames(Z) <- c("TRT", "SPP", "COMP",
"P_NP", "HTCB_2013")
pairs(Z, lower.panel = panel.smooth)
```



```{r}
library(stats)

plot.design(RGR_BA ~ TRT + SPP + COMP, data = growth_out)
with(growth_out, {
  interaction.plot(x.factor = TRT, trace.factor = SPP, response = RGR_BA, col = SPP, type = "l")
  interaction.plot(x.factor = SPP, trace.factor = TRT, response = RGR_BA)
  })
```

```{r}
growth_out %>% 
  group_by(TRT, SPP) %>% 
  summarize(mean_RGR_BA = mean(RGR_BA)) %>% 
  ggplot() + 
    geom_point(aes(x = TRT, y = mean_RGR_BA, group = SPP, col = SPP)) + 
    geom_line(aes(x = TRT, y = mean_RGR_BA, group = SPP, col = SPP))
```

```{r}
growth_out %>% 
  group_by(SPP, TRT) %>% 
  summarize(mean = mean(RGR_BA)) %>% 
  ggplot() + 
    geom_point(aes(x = SPP, y = mean, group = TRT, col = TRT)) + 
    geom_line(aes(x = SPP, y = mean, group = TRT, col = TRT))
```

```{r}
growth_out %>% 
  group_by(TRT, SPP) %>% 
  summarize(count = n())
```

```{r}
fgrow <- 
  growth_out %>% 
  filter(SPP %in% c("DF", "IC", "PP", "SP", "WF")) %>% 
  mutate(LCR_2018 = (HEIGHT_2018 - HTCB_2018)/HEIGHT_2018)
fgrow
fgrow$SPP <- factor(fgrow$SPP)
```

```{r}
plot.design(RGR_BA ~ TRT + SPP, data = fgrow)
with(fgrow, {
  interaction.plot(x.factor = TRT, trace.factor = SPP, response = RGR_BA, col = SPP, type = "l")
  interaction.plot(x.factor = SPP, trace.factor = TRT, response = RGR_BA, type = "l")
  })
```

```{r}
coplot(RGR_BA ~ TRT | SPP, data = fgrow)
```

```{r}
fit.lm <- gls(RGR_BA ~ TRT + SPP, data = fgrow)
summary(fit.lm)
vif(fit.lm)
```

```{r}
fit.ts.varts <- gls(RGR_BA ~ TRT + SPP, data = fgrow, weights = varIdent(form= ~ 1 | TRT * SPP))
summary(fit.ts.varts)
vif(fit.ts.varts)
```



```{r}
fit.all <- lm(RGR_BA ~ TRT + SPP + P_NP + HTCB_2013, data = fgrow)
step(fit.all)
```

```{r}
fit.tsh.vart <- gls(RGR_BA ~ TRT + SPP + HTCB_2013, data = fgrow, weights = varIdent(form= ~ 1 | TRT))
fit.tsh.varts <- gls(RGR_BA ~ TRT + SPP + HTCB_2013, data = fgrow, weights = varIdent(form= ~ 1 | TRT * SPP))

anova(fit.lm, fit.ts.varts, fit.tsh.vart, fit.tsh.varts)
```

```{r}
summary(fit.tsh.varts)
anova(fit.tsh.varts)
```

```{r}
plot(fit.tsh.varts)
std.res <- residuals(fit.tsh.varts, type = "pearson")
hist(std.res)
qqnorm(std.res)
plot(y = std.res, x = fgrow$TRT)
plot(y = std.res, x = fgrow$SPP)
plot(y = std.res, x = fgrow$HTCB_2013)
```

```{r}
fgrow %>% 
  group_by(TRT, SPP) %>% 
  summarize(mean_RGR_BA = mean(RGR_BA)) %>% 
  ggplot() + 
    geom_point(aes(x = TRT, y = mean_RGR_BA, group = SPP, col = SPP)) + 
    geom_line(aes(x = TRT, y = mean_RGR_BA, group = SPP, col = SPP))

fgrow %>% 
  group_by(SPP, TRT) %>% 
  summarize(mean_RGR_BA = mean(RGR_BA)) %>% 
  ggplot() + 
    geom_point(aes(x = SPP, y = mean_RGR_BA, group = TRT, col = TRT)) + 
    geom_line(aes(x = SPP, y = mean_RGR_BA, group = TRT, col = TRT))
```

```{r}
fgrow %>% 
  ggplot() + 
    geom_boxplot(aes(x = SPP, y = HTCB_2013))
```

```{r}
fgrow %>% 
  filter(SPP == "DF" & HTCB_2013 > 15)
```

```{r}
sample_size <- 
  fgrow %>% 
  group_by(TRT, SPP) %>% 
  count()
sample_size
  ggplot(sample_size) + 
    geom_col(aes(x = TRT, y = n, group = SPP, fill = SPP))
```


```{r}
ggplot(fgrow) + 
  geom_boxplot(aes(x = TRT, y = RGR_BA))
```

```{r}
ggplot(fgrow) + 
  geom_point(aes(x = HTCB_2013, y = RGR_BA))
```

```{r}
#contrasts(fgrow$SPP) <- contr.sum(levels(fgrow$SPP))
#contrasts(fgrow$COMP) <- contr.sum(levels(fgrow$COMP))
#contrasts(fgrow$TRT) <- contr.treatment(levels(fgrow$TRT), base = 2)
fit.tsc <- lm(RGR_BA ~ TRT + SPP + COMP + TRT:SPP, data = fgrow)
summary(fit.tsc)
anova(fit.tsc)
```

```{r}
fit.txs.varts <- gls(RGR_BA ~ TRT + SPP + TRT:SPP, data = fgrow, weights = varIdent(form= ~ 1 | TRT * SPP))
summary(fit.txs.varts)
anova(fit.txs.varts)
vif(fit.txs.varts)
```

```{r}
ggplot(fgrow) + 
  geom_point(aes(x = RGR_BA, y = TRT, col = SPP))

dotchart(x = fgrow$RGR_BA, groups = fgrow$TRT)
```

```{r}
sorted <- fgrow %>% 
  select(TRT, SPP, RGR_BA) %>% 
  arrange(TRT, SPP, RGR_BA)
dotchart(sorted$RGR_BA, groups = sorted$TRT, color = sorted$SPP, cex = 0.7)

sorted2 <- fgrow %>% 
  arrange(TRT, RGR_BA)
dotchart(sorted2$RGR_BA, groups = sorted$TRT, color = sorted$TRT, cex = 0.7)

fgrow %>% 
  group_by(TRT) %>% 
  summarize(mean = mean(RGR_BA)) %>% 
ggplot() + 
  geom_boxplot(data = fgrow, aes(x = TRT, y = RGR_BA, color = SPP)) + 
  geom_point(aes(x = TRT, y = mean), color = "red", shape = 4, size = 4)
```



```{r}
plot_ly(data = fgrow, x = ~TRT, y = ~SPP, z = ~RGR_BA, type = "scatter3d", color = ~COMP)
```

```{r}
fgrow %>% 
  filter(TRT == "M") %>% 
  group_by(COMP, SPP) %>% 
  count()

fgrow %>% 
  filter(TRT == "BB") %>% 
  group_by(COMP, SPP) %>% 
  count()

fgrow %>% 
  filter(TRT == "MBB") %>% 
  group_by(COMP, SPP) %>% 
  count()

fgrow %>% 
  filter(TRT == "MH") %>% 
  group_by(COMP, SPP) %>% 
  count()
```

```{r}
plot_ly(data = fgrow, x = ~TRT, y = ~SPP, z = ~COMP, type = "scatter3d")
```

```{r}
grow_RBA_ac <- 
  read.csv("grow_RBA_ac.csv") %>% 
  select(-X, -X.1, -X.2)
grow_RBA_ac
```

```{r}
grow_RBA_ac %>% 
  group_by(TRT) %>% 
  summarize(avg = mean(RBA_AC))

grow_RBA_ac %>% 
  ggplot() + 
  geom_boxplot(aes(x = TRT, y = RBA_AC))
```

```{r}
fgrow %>% 
  ggplot() + 
  geom_boxplot(aes(x = TRT, y = RGR_BA)) + 
  labs(x = 'Treatment', 
       y = 'Relative basal area growth rate')
```

```{r}
fit.txs.varts <- gls(RGR_BA ~ TRT + SPP + TRT:SPP, data = fgrow, weights = varIdent(form= ~ 1 | TRT * SPP))
summary(fit.txs.varts)
anova(fit.txs.varts)
```


```{r}
summary(lm(RGR_BA ~ TRT + SPP + COMP + TRT:SPP, data = fgrow))
```


